week4/w4d4/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :update, :show, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :update, :show, :destroy]

end

week4/w4d4/MusicApp/app/models/album.rb
class Album < ActiveRecord::Base
  validates :album_name, presence: true

  belongs_to :band
end

week4/w4d4/MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

week4/w4d4/MusicApp/app/models/band.rb
class Band < ActiveRecord::Base
  validates :band_name, presence: true

  has_many :albums
end

week4/w4d4/MusicApp/app/models/track.rb
class Track < ActiveRecord::Base
  validates :track_name, :album_id, presence: true

  belongs_to :album

  has_one :band,
    through: :album,
    source: :Band

end

week4/w4d4/MusicApp/app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    bc_obj = BCrypt::Password.new(self.password_digest)
    bc_obj.is_password?(password)
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end



end

week4/w4d4/MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new
    render 'new'
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      @band = @album.band
      flash.now[:errors] = @album.errors.full_messages
      render 'new'
    end
  end

  def edit
    @album = Album.find(params[:id])
    render 'edit'
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.new[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :album_name, :studio_or_live)
  end
end

week4/w4d4/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in(user)
    session[:session_token] = user.session_token
  end

  def log_out
    return if current_user.nil?
    current_user.reset_session_token!
  end
end

week4/w4d4/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
    render 'new'
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to bands_url
    else
      render 'new'
    end
  end

  private
  def band_params
    params.require(:band).permit(:band_name)
  end
end

week4/w4d4/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(session_params[:email], session_params[:password])
    if user
      log_in(user)
      flash[:errors] = ["Welcome back"]
      redirect_to user_url(user)
    else
      flash[:errors] = ["Invalid credentials"]
      redirect_to new_user_url
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end

  private
  def session_params
    params.require(:user).permit(:email, :password)
  end

end

week4/w4d4/MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new(album_id: params[:album_id])
    render 'new'
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      @album = track.album
      flash[:errors] = "Try again"
      render 'new'
    end
  end

  def edit
    @track = Track.find(params[:id])
    render 'edit'
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      render 'edit'
    end
  end

  def show
    @track = Track.find(params[:id])
    render 'show'
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to album_url(@track.album_id)
  end

  private

  def track_params
    params.require(:track).permit(:album_id, :track_name, :bonus_or_regular)
  end
end

week4/w4d4/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    if current_user.id = params[:id]
      @user = User.find(params[:id])
      render :show
    else
      redirect_to new_user_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end


end

week4/w4d4/MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

week4/w4d4/MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

week4/w4d4/MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
end

week4/w4d4/MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

week4/w4d4/MusicApp/app/views/albums/edit.html.erb
<h1>Edit album!</h1>

<form action="<%= albums_url %>" method="post">
  <input type="hidden" name="album_url(album)" method="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="band_id">Band Name</label><br>
  <select name="album[band_id]" id="band_id">
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>"
        <%= "selected" if @album.band_id == band.id %>>
        <%= band.band_name.upcase %>
    <% end %>
  </select><br><br>

  <label for="studio_or_live">Studio or Live</label><br>
    <input type="radio" name="album[studio_or_live]" value="studio"
     "checked" if album.studio_or_live == "studio">Studio<br>

    <input type="radio" name="album[studio_or_live]" value="live"
    "checked" if album.studio_or_live == "live">Live<br><br>
  </label>


  <label for="album_name">Album Name</label><br>
  <input type="text" name="album[album_name]" value="<%= @album.album_name %>"><br>

  <input type="submit" value="Edit Album">
</form>

week4/w4d4/MusicApp/app/views/albums/new.html.erb
<form action="<%= albums_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="band_id">Band Name</label><br>
  <select name="album[band_id]" id="band_id">
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>">
        <!-- <%#= "selected" if album.band_id == band.id %> -->
        <%= band.band_name.upcase %>
    <% end %>
  </select><br><br>

  <label for="studio_or_live">Studio or Live</label><br>
    <input type="radio" name="album[studio_or_live]" value="studio">Studio<br>
    <input type="radio" name="album[studio_or_live]" value="live">Live<br><br>
  </label>

  <label for="album_name">Album Name</label><br>
  <input type="text" name="album[album_name]"><br>

  <input type="submit" value="Add New Album">
</form>

week4/w4d4/MusicApp/app/views/albums/show.html.erb
<h2><%= @album.album_name %></h2>

<%= button_to "Delete Album", album_url(@album), method: :delete %>

week4/w4d4/MusicApp/app/views/bands/index.html.erb
<h1> All the bands</h1>
<ul>

  <% @bands.each do |band|%>
    <li><%= band.band_name %></li>
  <% end %>

</ul>

week4/w4d4/MusicApp/app/views/bands/new.html.erb
<h1>Add a new band!</h1>

<form action="<%= bands_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="band_name">Band Name</label><br>
  <input type="text" name="band[band_name]"><br>
  <input type="submit" value="Add New Band">
</form>

week4/w4d4/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/errors' %>

    <h1>Music App</h1>


    <%= yield %>


    <% if @current_user%>
      <%= button_to "Logout", session_url, method: :delete %>
    <% end %>

  </body>
</html>

week4/w4d4/MusicApp/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

week4/w4d4/MusicApp/app/views/tracks/new.html.erb
<form action="/tracks" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <h1>Add a new track</h1>

  <label for="album">Album</label>
  <select name="track[album_id]" id="track_album_id">
    <% Album.all.each do |album| %>
      <option value="<%= album.album_name %>"
        <%= "selected" if album.id == @track.album_id %>>
        <%= album.album_name.upcase %>
      </option>
    <% end %>
  </select>